name: IHNPro
favicon: null
layout_spectrum: 0.10014457860961556
typography_spectrum: 0.926575134973973
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.3275430628564209
  lightness: 0.21234864625148475
  saturation: 0.20405832398682833
  rhythmicContrast: 0.7705991356633604
purpose: []
